import { LandingTemplates } from "@/components/landing/landing-templates";
import { LandingCTA } from "@/components/landing/landing-cta";

export const metadata = {
  title: "Templates",
  description: "Explore the SEO formats generated by AI SEO Planner.",
};

export default function TemplatesPage() {
  return (
    <main className="pt-24 pb-12">
      <div className="text-center py-16 px-4">
        <h1 className="text-4xl md:text-5xl font-extrabold text-slate-deep mb-4">
          Output Formats
        </h1>
        <p className="text-lg text-ink-secondary max-w-2xl mx-auto">
          From Pillar Pages to Developer Guides, our engine structures content based on search intent.
        </p>
      </div>
      <LandingTemplates />
      <LandingCTA />
    </main>
  );
}
