import { PageHeader } from "@/components/page-header";

export const metadata = { title: "Terms & Conditions | AI SEO Planner" };

export default function TermsPage() {
  return (
    <main className="pt-24 pb-24 bg-canvas min-h-screen">
      <PageHeader badge="Legal" title="Terms & Conditions" description="Last updated: September 11, 2026" />
      <div className="max-w-4xl mx-auto px-4 mt-8">
        <div className="bg-white rounded-3xl p-8 md:p-12 border border-slate-200 shadow-sm">
          <h2 className="text-2xl font-bold text-slate-deep mb-4 mt-2">1. Acceptance of Terms</h2>
          <p className="text-slate-600 mb-8 leading-relaxed text-lg">By accessing and using AI SEO Planner, you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, you may not access the service.</p>
          <h2 className="text-2xl font-bold text-slate-deep mb-4 mt-8">2. Use License</h2>
          <p className="text-slate-600 mb-8 leading-relaxed text-lg">We grant you a personal, non-transferable license to use our platform. You may not attempt to reverse engineer our generation algorithms or use our API endpoints outside of the provided interface.</p>
          <h2 className="text-2xl font-bold text-slate-deep mb-4 mt-8">3. Fair Use of AI Generation</h2>
          <p className="text-slate-600 mb-8 leading-relaxed text-lg">Users on unlimited plans are subject to a fair use policy to prevent abuse of the underlying LLM infrastructure. Automated scraping or botting of the input field is strictly prohibited.</p>
          <h2 className="text-2xl font-bold text-slate-deep mb-4 mt-8">4. Disclaimer</h2>
          <p className="text-slate-600 mb-4 leading-relaxed text-lg">The SEO strategies generated by our platform are recommendations based on current search algorithms. We do not guarantee specific ranking positions or traffic volumes on Google.</p>
        </div>
      </div>
    </main>
  );
}
